### ISSUE TITLE
如何自定义http请求的超时时间？

### ISSUE THREAD

**Issue by leizongmin** [aliyun/aliyun-openapi-nodejs-sdk#16]
程序在执行期间，偶尔会抛出如下错误：

```
{ RequestTimeoutError: Timeout(3000). POST http://mt.cn-hangzhou.aliyuncs.com/api/translate/web/general failed.
    at Timeout.setTimeout [as _onTimeout] (~/node_modules/httpx/lib/index.js:113:17)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  name: 'RequestTimeoutError',
  message:
   'Timeout(3000). POST http://mt.cn-hangzhou.aliyuncs.com/api/translate/web/general failed.' }
```

客户端默认的超时时间是3秒，请问如何自定义http请求的超时时间？

**Comment by JacksonTian** [comment]
ROA 吗。 client 的构造函数里增加 timeout

**Comment by leizongmin** [comment]
```javascript
const Client = require("@alicloud/alimt-2019-01-02");

const client = new Client({
  accessKeyId: "xxxxx",
  accessKeySecret: "xxxxx",
  endpoint: "http://mt.cn-hangzhou.aliyuncs.com",
  timeout: 10000, // 没有效果
});
```

**Comment by JacksonTian** [comment]
```js
new Client({
  opts: {
    timeout: 5000
  }
})
```

**Comment by Momo707577045** [comment]
关键字是：readTimeout，亲测可行

const client = new Client({
  accessKeyId: "xxxxx",
  accessKeySecret: "xxxxx",
  readTimeout: 10000,
});
